name = "assetmantle-webapp"
type = "webpack"
zone_id = '4d52f36b396dad8cddd83b3d5e0fbda4'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-11-01"


[env.demo]
routes = ['https://demo.assetmantle.one/*']
