name = "assetmantle-webapp"
type = "webpack"
zone_id = '56f80f9b92647da8867be957889b2281'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-11-01"


[env.demo]
routes = ['https://demo.app.assetmantle.one/*']