export const lightTheme = {
    body: '#262A2B',
    fontFamily: 'Poppins, sans-serif;',
    text: '#FAFAFA',
    toggleBorder: '#fff',
    gradient: 'linear-gradient(#39598A, #79D7ED)',
    navigationBackground: 'transparent',
    signupBackground: '#F5F5F5',
    navLinkColor: '#999999',
    ActiveNavLinkColor: '#fff',
    cardTextColor: '#363537',
    modalHeaderBorderColor: 'rgba(38, 42, 43, 0.06)',
    inputFieldBackground: '#fff',
    inputFieldBorderColor: '#ced4da',
    inputFieldTextColor: '#495057',
    modalCloseIconColor: '#000',
    tabBackground: '#dee2e6',
    tabNavLinkBorderColor: '#e9ecef #e9ecef #dee2e6',
    tabActiveNavLinkColor: '#495057',
    bannerHeadingColor: '#FFFFFF',
    bannerContentColor: '#818485',
    modalHeaderColor: '#262A2B',
    primaryButtonBackground: '#efcc30',
    primaryButtonColor: '#262a2b'

}

export const darkTheme = {
    body: '#121212',
    text: '#FAFAFA',
    fontFamily: 'Poppins, sans-serif;',
    toggleBorder: '#6B8096',
    gradient: 'linear-gradient(#091236, #1E215D)',
    navigationBackground: 'transparent',
    signupBackground: '#1d1d1d',
    navLinkColor: '999999',
    ActiveNavLinkColor: '#6c757d',
    cardTextColor: '#FAFAFA',
    modalHeaderBorderColor: '#6B8096',
    inputFieldBackground: '#132a47',
    inputFieldBorderColor: '#132a47',
    inputFieldTextColor: '#e5ecf3',
    modalCloseIconColor: '#e5e5e5',
    tabBackground: '#112641',
    tabNavLinkBorderColor: '#18365b #18365b #18365b',
    tabActiveNavLinkColor: '#a8bcdb',
    bannerHeadingColor: '#FFFFFF',
    bannerContentColor: '#818485',
    modalHeaderColor: '#262A2B',
    primaryButtonBackground: '#efcc30',
    primaryButtonColor: '#262a2b'
}
