const TENDERMINT_API_URL = process.env.REACT_APP_API_KEY;
const ASSETMANTLE_API_URL = process.env.REACT_APP_ASSET_MANTLE_API;
export const getBlockURL = (searchText) => `${TENDERMINT_API_URL}/block?height=${searchText}`;
// export const getStatusURL = () => `${TENDERMINT_API_URL}/status`;
export const getLatestBlockURL = () => `${TENDERMINT_API_URL}/block`;
export const getValidatorsURL = () => `${ASSETMANTLE_API_URL}/staking/validators`;
export const getBlocksURL = (min, max) => `${TENDERMINT_API_URL}/blockchain?minHeight=${min}&maxHeight=${max}`;
export const getBlockHeightURL = (height) => `${TENDERMINT_API_URL}/block_results?height=${height}`;
export const getTransactionURL = (txHash) => `${TENDERMINT_API_URL}/tx?hash=0x${txHash}&prove=true`;
export const getBlockByHashURL = (blockHash) => `${TENDERMINT_API_URL}/block_by_hash?hash=0x${blockHash}`;
export const getBlockTransactionsURL = (blockHeight) => `${TENDERMINT_API_URL}/tx_search?query=tx.height%3D${blockHeight}&prove=true&page=1&per_page=30&order_by=asc`;
export const addAccountURL = () => `${ASSETMANTLE_API_URL}/keys/add`;
export const recoverAccountURL = () => `${ASSETMANTLE_API_URL}/keys/recover`;
export const getTxsURL = (hash) => `${ASSETMANTLE_API_URL}/txs/${hash}`;
export const senCoinURL = (toAddress) => `${ASSETMANTLE_API_URL}/bank/accounts/${toAddress}/transfers`;
export const assetOrderURL = () => `${ASSETMANTLE_API_URL}/xprt/orders/orders/_`;
export const buyAssetHashURL = (hash) => `${ASSETMANTLE_API_URL}/xprt/metas/metas/${hash}`;
export const orderTakeURL = () => `${ASSETMANTLE_API_URL}/xprt/orders/take`;
export const assetsURL = () => `${ASSETMANTLE_API_URL}/xprt/assets/assets/_`;
export const buyAssetSplitsURL = () => `${ASSETMANTLE_API_URL}/xprt/splits/splits/_`;
export const buyAssetIdentitiesURL = () => `${ASSETMANTLE_API_URL}/xprt/identities/identities/_`;
export const splitSendURL = () => `${ASSETMANTLE_API_URL}/xprt/splits/send`;
export const OrdreMakeURL = () => `${ASSETMANTLE_API_URL}/xprt/orders/make`;
export const classificationsURL = () => `${ASSETMANTLE_API_URL}/xprt/classifications/classifications/_`;
export const assetMintURL = () => `${ASSETMANTLE_API_URL}/xprt/assets/mint`;
export const assetBurnURL = () => `${ASSETMANTLE_API_URL}/xprt/assets/burn`;
export const OrderCancelURL = () => `${ASSETMANTLE_API_URL}/xprt/orders/cancel`;
export const IssueIdentityURL = () => `${ASSETMANTLE_API_URL}/xprt/identities/issue`;
export const splitWrapURL = () => `${ASSETMANTLE_API_URL}/xprt/splits/wrap`;
export const deputizeURL = () => `${ASSETMANTLE_API_URL}/xprt/maintainers/deputize`;
export const maintainersURL = () => `${ASSETMANTLE_API_URL}/xprt/maintainers/maintainers/_`;

