---
name: Staging 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Install dependencies
        run: npm ci
      - name: Build react project
        run: npm run build
        env:
          REACT_APP_API_KEY: 'http://api.demo.assetmantle.persistence.one/rpc'
          REACT_APP_ASSET_MANTLE_API: 'http://api.demo.assetmantle.persistence.one/rest'
          REACT_APP_FAUCET_SERVER: 'http://api.demo.assetmantle.persistence.one/faucet'
          REACT_APP_TENDERMINT_RPC_ENDPOINT: 'http://api.demo.assetmantle.persistence.one/rpc'
          REACT_APP_CHAIN_ID: 'test'
          REACT_APP_CHAIN_NAME: 'AssetMantle'
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          environment: 'staging'
